- name: Deploy and Configure LAMP Stack
  hosts: all
  become: true
  vars_files:
   - wordpress-playbook/group_vars/wordpress/main.yml
  roles:
    - update
    - apache
    - mariadb
    - php
    - wordpress
